AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Repository responsible for polling data from SQS, parse to desired format, and to persist it on some Storage

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Parameters:
    QueueName:
        Type: String
        Description: Name of the queue to poll from
        Default: on-place-scrapped

Resources:

  OnReceivePlaceUpdateEvent:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: main.on_receive_change_pass_request
      Runtime: python3.9
      Layers:
          - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:4
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref QueueName
      Events:
        OnMessageAvailable:
          Type: SQS
          Properties:
            Queue: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${QueueName}
            BatchSize: 5 # Maximum number of messages to process per function invocation.
            Enabled: true
